"""Remove  markdownFormPost table

Revision ID: 01017264bb0b
Revises: bff307aebbf3
Create Date: 2020-10-25 09:42:36.510783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01017264bb0b'
down_revision = 'bff307aebbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_markdown_form_post_timestamp', table_name='markdown_form_post')
    op.drop_table('markdown_form_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markdown_form_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=500), nullable=True),
    sa.Column('body_html', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_markdown_form_post_timestamp', 'markdown_form_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
