"""hello world table

Revision ID: 013bddc76b8a
Revises: a8142124d828
Create Date: 2020-11-19 13:48:42.298936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013bddc76b8a'
down_revision = 'a8142124d828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello_world_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hello_world_post_timestamp'), 'hello_world_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hello_world_post_timestamp'), table_name='hello_world_post')
    op.drop_table('hello_world_post')
    # ### end Alembic commands ###
