"""flask bootstrap table

Revision ID: 0ee946e32f49
Revises: ec97e9f3892d
Create Date: 2021-03-16 04:15:29.752994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee946e32f49'
down_revision = 'ec97e9f3892d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_bootstrap_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flask_bootstrap_post_timestamp'), 'flask_bootstrap_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flask_bootstrap_post_timestamp'), table_name='flask_bootstrap_post')
    op.drop_table('flask_bootstrap_post')
    # ### end Alembic commands ###
