"""rich text table

Revision ID: 20357c0dbacf
Revises: 2986936761a6
Create Date: 2020-11-19 19:30:46.557656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20357c0dbacf'
down_revision = '2986936761a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rich_text_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rich_text_post_timestamp'), 'rich_text_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rich_text_post_timestamp'), table_name='rich_text_post')
    op.drop_table('rich_text_post')
    # ### end Alembic commands ###
