"""docker table

Revision ID: 247cb1ec168d
Revises: dece2e4b3dea
Create Date: 2020-11-14 16:55:33.668894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247cb1ec168d'
down_revision = 'dece2e4b3dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('install_docker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_docker_timestamp'), 'install_docker', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_install_docker_timestamp'), table_name='install_docker')
    op.drop_table('install_docker')
    # ### end Alembic commands ###
