"""dates and time table

Revision ID: 286b98e52b84
Revises: 0ee946e32f49
Create Date: 2021-03-16 10:11:09.542559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286b98e52b84'
down_revision = '0ee946e32f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dates_and_time_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dates_and_time_post_timestamp'), 'dates_and_time_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dates_and_time_post_timestamp'), table_name='dates_and_time_post')
    op.drop_table('dates_and_time_post')
    # ### end Alembic commands ###
