"""Remove hello world table

Revision ID: 289583794a9d
Revises: 706ffe8a3114
Create Date: 2020-11-14 22:19:25.451132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289583794a9d'
down_revision = '706ffe8a3114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hello_world_post_timestamp', table_name='hello_world_post')
    op.drop_table('hello_world_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello_world_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=500), nullable=True),
    sa.Column('body_html', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hello_world_post_timestamp', 'hello_world_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
