"""new field in portfolio table relationship

Revision ID: 2adef5ab9c45
Revises: 4c7ccb6401b7
Create Date: 2021-05-08 02:55:27.304903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adef5ab9c45'
down_revision = '4c7ccb6401b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_portfolio_list_admin_id_admin'), 'admin', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_list', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_portfolio_list_admin_id_admin'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
