"""allow comment field in heroku table

Revision ID: 492b909522ef
Revises: 5d568739cef8
Create Date: 2021-05-19 13:26:34.428987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492b909522ef'
down_revision = '5d568739cef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroku_deployment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_comment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroku_deployment', schema=None) as batch_op:
        batch_op.drop_column('allowed_comment')

    # ### end Alembic commands ###
