"""Articles table

Revision ID: 4c01073d1a5d
Revises: f654aa0e189e
Create Date: 2020-11-22 17:54:20.304969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c01073d1a5d'
down_revision = 'f654aa0e189e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('link', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_list_content'), 'articles_list', ['content'], unique=False)
    op.create_index(op.f('ix_articles_list_date_posted'), 'articles_list', ['date_posted'], unique=False)
    op.create_index(op.f('ix_articles_list_link'), 'articles_list', ['link'], unique=False)
    op.create_index(op.f('ix_articles_list_title'), 'articles_list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_list_title'), table_name='articles_list')
    op.drop_index(op.f('ix_articles_list_link'), table_name='articles_list')
    op.drop_index(op.f('ix_articles_list_date_posted'), table_name='articles_list')
    op.drop_index(op.f('ix_articles_list_content'), table_name='articles_list')
    op.drop_table('articles_list')
    # ### end Alembic commands ###
