"""Remove virtualenvwrapper table

Revision ID: 524ff301cee4
Revises: a9bb24756783
Create Date: 2020-10-24 07:42:44.754682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524ff301cee4'
down_revision = 'a9bb24756783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_virtualenvwrapper_post_timestamp', table_name='virtualenvwrapper_post')
    op.drop_table('virtualenvwrapper_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtualenvwrapper_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=5), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_virtualenvwrapper_post_timestamp', 'virtualenvwrapper_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
