"""Add heroku model

Revision ID: 597a0009abb9
Revises: e7fc4452bfcf
Create Date: 2020-11-05 13:23:40.448784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597a0009abb9'
down_revision = 'e7fc4452bfcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroku_deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroku_deployment_timestamp'), 'heroku_deployment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroku_deployment_timestamp'), table_name='heroku_deployment')
    op.drop_table('heroku_deployment')
    # ### end Alembic commands ###
