"""heroku deployment table

Revision ID: 678a1e5fbba4
Revises: cdaf115b9ea2
Create Date: 2020-11-19 19:34:00.958166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678a1e5fbba4'
down_revision = 'cdaf115b9ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroku_deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroku_deployment_timestamp'), 'heroku_deployment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroku_deployment_timestamp'), table_name='heroku_deployment')
    op.drop_table('heroku_deployment')
    # ### end Alembic commands ###
