"""rename webdev field to allow comment

Revision ID: 6ee66bda73f2
Revises: e5760f29abbc
Create Date: 2021-05-08 05:18:28.429467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee66bda73f2'
down_revision = 'e5760f29abbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_development_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_comment', sa.Boolean(), nullable=True))
        batch_op.drop_column('allowed_article')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_development_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_article', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('allowed_comment')

    # ### end Alembic commands ###
