"""new verification phone field

Revision ID: 748bc55ded56
Revises: 2ad2f86cf082
Create Date: 2021-05-01 08:49:54.632865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748bc55ded56'
down_revision = '2ad2f86cf082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_phone', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('verification_phone')

    # ### end Alembic commands ###
