"""allow comment field in flask bootstrap table

Revision ID: 816062ea69db
Revises: 9c37679e1fd4
Create Date: 2021-05-12 19:31:35.067527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816062ea69db'
down_revision = '9c37679e1fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_bootstrap_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_comment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask_bootstrap_post', schema=None) as batch_op:
        batch_op.drop_column('allowed_comment')

    # ### end Alembic commands ###
