"""allowed field in virtualenv table

Revision ID: 938dda2c917f
Revises: fc18a80db3fd
Create Date: 2021-05-12 02:55:03.458128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938dda2c917f'
down_revision = 'fc18a80db3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtualenvwrapper_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_comment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtualenvwrapper_post', schema=None) as batch_op:
        batch_op.drop_column('allowed_comment')

    # ### end Alembic commands ###
