"""update VagrantPost table with richtext 

Revision ID: 97af0c4b5340
Revises: fecaf46dfead
Create Date: 2020-10-24 04:36:27.467773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97af0c4b5340'
down_revision = 'fecaf46dfead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vagrant_post', sa.Column('body_html', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vagrant_post', 'body_html')
    # ### end Alembic commands ###
