"""virtualenvwrapper table

Revision ID: a4636054d94e
Revises: 53ff35bcea06
Create Date: 2020-11-19 13:10:28.916954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4636054d94e'
down_revision = '53ff35bcea06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtualenvwrapper_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtualenvwrapper_post_timestamp'), 'virtualenvwrapper_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtualenvwrapper_post_timestamp'), table_name='virtualenvwrapper_post')
    op.drop_table('virtualenvwrapper_post')
    # ### end Alembic commands ###
