"""status field in articles table

Revision ID: b2b3cc7e438f
Revises: 4ee665780c8a
Create Date: 2021-04-30 11:16:15.931915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b3cc7e438f'
down_revision = '4ee665780c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_article', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles_list', schema=None) as batch_op:
        batch_op.drop_column('allowed_article')

    # ### end Alembic commands ###
