"""update PersonalBlogPost table with richtext 

Revision ID: cc4a4fbfd810
Revises: 97af0c4b5340
Create Date: 2020-10-24 04:37:51.227262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4a4fbfd810'
down_revision = '97af0c4b5340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_blog_post', sa.Column('body_html', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_blog_post', 'body_html')
    # ### end Alembic commands ###
