"""twilio sendgrid table

Revision ID: cedede6c29f7
Revises: c70196d0780d
Create Date: 2021-04-02 17:25:03.455886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedede6c29f7'
down_revision = 'c70196d0780d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twilio_send_grid_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twilio_send_grid_post_timestamp'), 'twilio_send_grid_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twilio_send_grid_post_timestamp'), table_name='twilio_send_grid_post')
    op.drop_table('twilio_send_grid_post')
    # ### end Alembic commands ###
