"""allow comment field in webdev table

Revision ID: e5760f29abbc
Revises: 2adef5ab9c45
Create Date: 2021-05-08 05:10:29.854159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5760f29abbc'
down_revision = '2adef5ab9c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_development_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_article', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_development_post', schema=None) as batch_op:
        batch_op.drop_column('allowed_article')

    # ### end Alembic commands ###
