"""portfolio table

Revision ID: ec97e9f3892d
Revises: 62dbadf9b391
Create Date: 2020-11-25 12:24:52.650757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec97e9f3892d'
down_revision = '62dbadf9b391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('github_link', sa.String(length=140), nullable=True),
    sa.Column('contributor_link', sa.String(length=140), nullable=True),
    sa.Column('project_design_link', sa.String(length=300), nullable=True),
    sa.Column('live_project_link', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_list_contributor_link'), 'portfolio_list', ['contributor_link'], unique=False)
    op.create_index(op.f('ix_portfolio_list_date_posted'), 'portfolio_list', ['date_posted'], unique=False)
    op.create_index(op.f('ix_portfolio_list_github_link'), 'portfolio_list', ['github_link'], unique=False)
    op.create_index(op.f('ix_portfolio_list_live_project_link'), 'portfolio_list', ['live_project_link'], unique=False)
    op.create_index(op.f('ix_portfolio_list_overview'), 'portfolio_list', ['overview'], unique=False)
    op.create_index(op.f('ix_portfolio_list_project_design_link'), 'portfolio_list', ['project_design_link'], unique=False)
    op.create_index(op.f('ix_portfolio_list_title'), 'portfolio_list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_list_title'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_project_design_link'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_overview'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_live_project_link'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_github_link'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_date_posted'), table_name='portfolio_list')
    op.drop_index(op.f('ix_portfolio_list_contributor_link'), table_name='portfolio_list')
    op.drop_table('portfolio_list')
    # ### end Alembic commands ###
