"""update reCaptcha table with richtext 

Revision ID: fecaf46dfead
Revises: 209eef9dcb38
Create Date: 2020-10-24 04:34:43.424016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecaf46dfead'
down_revision = '209eef9dcb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('re_captcha_post', sa.Column('body_html', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('re_captcha_post', 'body_html')
    # ### end Alembic commands ###
